[tool.poetry]
name = "the-caverns"
version = "0.0.0"
description = "An exploration ARPG game made in python with pygame."
authors = ["LGgameLAB"]
license = "None"

[tool.poetry.dependencies]
python = "^3.8"
PyTMX = "^3.31"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
